### ISSUE TITLE
Any plans to make it available on the nuget.org

### ISSUE THREAD

**Issue by mahdighorbanpour** [telstra/DigitalTwins-CodeFirst-dotnet#1]
Hi,
Nice job, you made the it definitely easier for developers to start with Azure digital twins. Do you have any plans to register a package on nuget.org?

**Comment by kavink98** [comment]
Yes this package will be available on Nuget latest by next week

**Comment by mahdighorbanpour** [comment]
great, thank

**Comment by DMaxwell02** [comment]
Though this issue appears to be closed, I don't see it on NuGet as a public package yet. (22 days later after @kavink98 mentioned it would be on Nuget "latest by next week"). 

In the time being I am trying to create a private copy and a private NuGet package since I work on different computers and it is a hassle to redo the paths of the telstra Twins referenced projects each time updating source control.

**Comment by sgryphon** [comment]
I opened a new issue (#20) for actually getting it on Nuget (as this issue was technically only asking if there were plans ... yes, there were plans ... they just didn't happen ... I presume there are more plans ... :-)
